// Copyright 2023 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
// SPDX-License-Identifier: GPL-3.0-or-later

// #include "rgb/anim/flower_blooming.h" // super pretty
// #include "rgb/anim/startup_swirl_anim.h" // doesn't work correctly. Not sure why.
// #include "rgb/anim/my_party_rocks.h" // seizure warning
#include "rgb/anim/cool_diagonal.h" // neaat
#include "rgb/anim/random_breath_rainbow.h" // rgb vomit!
// #include "rgb/anim/custom_gradient.h" // too custom
#include "rgb/anim/raindrops.h"
